MediaCodec.cpp: Remove redefinition of duplicate classes frameworks/av/media/libstagefright/MediaCodec.cpp:283:48: error: redefinition of 'sLockCookies' Mutex MediaCodec::ResourceManagerServiceProxy::sLockCookies;                                                ^ frameworks/av/media/libstagefright/MediaCodec.cpp:267:48: note: previous definition is here Mutex MediaCodec::ResourceManagerServiceProxy::sLockCookies;                                                ^ frameworks/av/media/libstagefright/MediaCodec.cpp:284:58: error: redefinition of 'sCookies' std::set<void*> MediaCodec::ResourceManagerServiceProxy::sCookies;                                                          ^ frameworks/av/media/libstagefright/MediaCodec.cpp:268:58: note: previous definition is here std::set<void*> MediaCodec::ResourceManagerServiceProxy::sCookies;                                                          ^ frameworks/av/media/libstagefright/MediaCodec.cpp:287:47: error: redefinition of 'addCookie' void MediaCodec::ResourceManagerServiceProxy::addCookie(void* cookie) {                                               ^ frameworks/av/media/libstagefright/MediaCodec.cpp:271:47: note: previous definition is here void MediaCodec::ResourceManagerServiceProxy::addCookie(void* cookie) {                                               ^ frameworks/av/media/libstagefright/MediaCodec.cpp:293:47: error: redefinition of 'removeCookie' void MediaCodec::ResourceManagerServiceProxy::removeCookie(void* cookie) {                                               ^ frameworks/av/media/libstagefright/MediaCodec.cpp:277:47: note: previous definition is here void MediaCodec::ResourceManagerServiceProxy::removeCookie(void* cookie) {                                               ^ 4 errors generated.
Fixed Mismerge in commit 72d276949b09acc5715801b7b1f6b56b0f90f4f5